export const qoutes = [
    "Live life as if everything is rigged in your favor.",
    "The universe is not outside of you. Look inside yourself; everything that you want, you already are.",
    "We cannot teach people anything; we can only help them discover it within themselves.",
    "It isn't having your questions answered, it’s about having your answers questioned.",
    "It is not in the pursuit of happiness that we find fulfillment, it is in the happiness of pursuit.",
    "Life grows relative to one's investment in it.",
    "Even if you stumble, you're still moving forward.",
    "Be faithful to that which exists within yourself.",
    "Impossible is for the unwilling.",
    "It's only after you've stepped outside your comfort zone that you begin to change, grow, and transform.",
    "If it matters to you, you'll find a way.",
    "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
    "No one can make you feel inferior without your consent.",
    "Life is fragile. We're not guaranteed a tomorrow so give it everything you've got.",
    "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it.",
    "Whether you think you can, or think you can't. You're right.",
    "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.",
    "Be yourself; everyone else is already taken.",
    "Change the way you look at things and the things you look at change.",
    "Hope is a waking dream.",
    "Don't let someone who gave up on their dreams talk you out of yours.",
    "Happiness is not the absence of problems, it's the ability to deal with them.",
    "Learn the rules like a pro, so you can break them like an artist.",
    "If opportunitiy doesn't knock, build a door.",
    "If you want to achieve greatness stop asking for permission.",
    "The meaning of life is to find your gift. The purpose of life is to give it away.",
    "Failure is the condiment that gives success its flavor.",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
    "The ambitious take pride in their achievements, the wise in their failures, and the cowardly in their indifference.",
    "The human who moves a mountain begins by carrying away small stones.",
    "Grow through what you go through.",
    "The only place where success comes before work is in the dictionary.",
    "Set your life on fire. Seek those who fan your flames.",
    "Gratitude is the wine for the soul. Go on. Get drunk.",
    "The only person you are destined to become is the person you decide to be.",
    "There is only one corner of the universe you can be certain of improving, and that's your own self.",
    "The most reliable way to predict the future is to create it.",
    "You cannot swim for new horizons until youi have courage to lose sight of the shore.",
    "Ten years of coaching without reflection, is simply one year of coaching repeated ten times.",
    "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third, by experience, which is the bitterest."
];